[20200711]
date = 2020-07-11
name = "Presidential Primary"
original_date = 2020-06-20
sources = [
    "https://www.sos.la.gov/ElectionsAndVoting/GetElectionInformation/Pages/default.aspx",
    "https://www.sos.la.gov/ElectionsAndVoting/PublishedDocuments/LouisianaElectionQuickFacts.pdf"
]

[20200711.registration]
received_by = 2020-06-10
in_person_by = 2020-06-10
online_by = 2020-06-20
sources = [
    "https://www.sos.la.gov/ElectionsAndVoting/GetElectionInformation/Pages/default.aspx", 
    "https://www.sos.la.gov/ElectionsAndVoting/PublishedDocuments/LouisianaElectionQuickFacts.pdf"
]

[20200711.absentee.application]
received_by = 2020-07-07T16:30
sources = [
    "https://www.sos.la.gov/ElectionsAndVoting/GetElectionInformation/Pages/default.aspx",
    "https://www.sos.la.gov/ElectionsAndVoting/PublishedDocuments/LouisianaElectionQuickFacts.pdf"
]

[20200711.absentee]
received_by = 2020-07-10T16:30:00
sources = [
    "https://www.sos.la.gov/ElectionsAndVoting/GetElectionInformation/Pages/default.aspx",
    "https://www.sos.la.gov/ElectionsAndVoting/PublishedDocuments/LouisianaElectionQuickFacts.pdf"
]

[20200711.poll.early]
in_person_start = 2020-06-20
in_person_by = 2020-07-04
sources = [
    "https://www.sos.la.gov/ElectionsAndVoting/GetElectionInformation/Pages/default.aspx",
    "https://www.sos.la.gov/ElectionsAndVoting/PublishedDocuments/LouisianaElectionQuickFacts.pdf"
]

[20200711.poll]
in_person_start = 2020-07-11T07:00:00
in_person_by = 2020-07-11T20:00:00
sources = [
    "https://www.sos.la.gov/ElectionsAndVoting/PublishedDocuments/LouisianaElectionQuickFacts.pdf"
]

[20200815]
date = 2020-08-15
name = " Municipal General Election"
original_date = 2020-07-25
sources = [
    "https://www.sos.la.gov/ElectionsAndVoting/GetElectionInformation/Pages/default.aspx"
]

[20200815.registration]
in_person_by = 2020-07-15
received_by  = 2020-07-15
online_by = 2020-07-25  
sources = [
    "https://www.sos.la.gov/ElectionsAndVoting/GetElectionInformation/Pages/default.aspx"
]

[20200815.absentee.application]
received_by = 2020-08-11T16:30:00
sources = [
    "https://www.sos.la.gov/ElectionsAndVoting/GetElectionInformation/Pages/default.aspx"
]

[20200815.absentee]
received_by = 2020-08-14T16:30:00
sources = [
    "https://www.sos.la.gov/ElectionsAndVoting/GetElectionInformation/Pages/default.aspx"
]

[20200815.poll.early]
in_person_start = 2020-07-25T08:30:00
in_person_by = 2020-08-08T18:00:00
sources = [
    "https://www.sos.la.gov/ElectionsAndVoting/GetElectionInformation/Pages/default.aspx"
]

[20200815.poll]
in_person_start = 2020-08-15T07:00:00
in_person_by = 2020-08-15T20:00:00
sources = [] # Assumed based on other election

[20201103]
date = 2020-11-03
name = "General"
original_date = 2020-11-03
sources = [
    "https://www.sos.la.gov/ElectionsAndVoting/GetElectionInformation/Pages/default.aspx"
]

[20201103.registration]
in_person_by = 2020-10-05
received_by = 2020-10-05
online_by = 2020-10-13
sources = [
    "https://www.sos.la.gov/ElectionsAndVoting/GetElectionInformation/Pages/default.aspx"
]

[20201103.absentee.application]
received_by = 2020-10-30T16:30:00
sources = [
    "https://www.sos.la.gov/ElectionsAndVoting/GetElectionInformation/Pages/default.aspx"
]


[20201103.absentee]
received_by = 2020-11-02T16:30:00
sources = [
    "https://www.sos.la.gov/ElectionsAndVoting/GetElectionInformation/Pages/default.aspx"
]

[20201103.poll.early]
in_person_start = 2020-10-20T08:30:00
in_person_by = 2020-10-27T18:00:00
sources = [
    "https://www.sos.la.gov/ElectionsAndVoting/GetElectionInformation/Pages/default.aspx"
]

[20201103.poll]
in_person_start = 2020-11-03T07:00:00
in_person_by = 2020-11-03T20:00:00
sources = [] # Assumed based on other election

[20201205]
date = 2020-12-05
name = "Congressional and Open General Election"
original_date = 2020-12-05
sources = [
    "https://www.sos.la.gov/ElectionsAndVoting/GetElectionInformation/Pages/default.aspx"
]

[20201205.registration]
in_person_by = 2020-11-04
received_by = 2020-11-04
online_by = 2020-11-14
sources = [
    "https://www.sos.la.gov/ElectionsAndVoting/GetElectionInformation/Pages/default.aspx"
]

[20201205.absentee.application]
received_by = 2020-12-01T16:30:00
sources = [
    "https://www.sos.la.gov/ElectionsAndVoting/GetElectionInformation/Pages/default.aspx"
]

[20201205.absentee]
received_by = 2020-12-04T16:30:00
sources = [
    "https://www.sos.la.gov/ElectionsAndVoting/GetElectionInformation/Pages/default.aspx"
]

[20201205.poll.early]
in_person_start = 2020-11-20T08:30:00
in_person_by = 2020-11-28T18:00:00
sources = [
    "https://www.sos.la.gov/ElectionsAndVoting/GetElectionInformation/Pages/default.aspx"
]

[20201205.poll]
in_person_start = 2020-12-05T07:00:00
in_person_by = 2020-12-05T20:00:00
sources = [] # Assumed based on other election
