[20200303]
date = 2020-03-03
name = "Presidential Primary"
original_date = 2020-03-03

[20200806]
date = 2020-08-06
name = "Congressional Primary"
original_date = 2020-08-06

[20200806.registration]
online_by = 2020-07-07
postmarked_by = 2020-07-07
in_person_by = 2020-07-07
sources = [
    "https://sos.tn.gov/products/elections/2020-election-calendar",
    "https://sos.tn.gov/products/elections/how-do-i-register-vote"
]

[20200806.absentee.application]
receive_start = 2020-05-08
received_by = 2020-07-30
sources = ["https://sos.tn.gov/products/elections/2020-election-calendar"]

[20200806.asbsentee]
received_by = 2020-08-06T20:00:00 # 8:00 p.m. EST / 7:00 p.m. CST.

[20200806.poll.early]
in_person_start = 2020-07-17
in_person_by = 2020-08-01
sources = ["https://sos.tn.gov/products/elections/2020-election-calendar"]

[20200806.poll]
in_person_start = 2020-08-06 # Times vary by county
in_person_by = 2020-08-06T20:00:00 # 8:00 p.m. EST / 7:00 p.m. CST.
sources = [
    "https://sos.tn.gov/products/elections-executive/presidential-preference-primary-election"
]

[20201103]
date = 2020-11-03
name = "General"
original_date = 2020-11-03
sources = ["https://sos.tn.gov/products/elections/2020-election-calendar"]

[20201103.registration]
online_by = 2020-10-05
postmarked_by = 2020-10-05
in_person_by = 2020-10-05
sources = [
    "https://sos.tn.gov/products/elections/2020-election-calendar",
    "https://sos.tn.gov/products/elections/how-do-i-register-vote"
]

[20201103.absentee.application]
receive_start = 2020-08-05
received_by = 2020-10-27
sources = ["https://sos.tn.gov/products/elections/2020-election-calendar"]

[20201103.asbsentee]
received_by = 2020-11-03T20:00:00 # 8:00 p.m. EST / 7:00 p.m. CST.

[20201103.poll.early]
in_person_start = 2020-10-14
in_person_by = 2020-10-29
sources = ["https://sos.tn.gov/products/elections/2020-election-calendar"]

[20201103.poll]
in_person_start = 2020-11-03 # time varies by County
in_person_by = 2020-11-03T20:00:00 # 8:00 p.m. EST / 7:00 p.m. CST.
sources = [
    "https://sos.tn.gov/products/elections-executive/presidential-preference-primary-election"
]
