[20200303]
date = 2020-03-03
name = "Presidential Primary"
original_date = 2020-03-03

[20200811]
date = 2020-08-11
name = "Congressional Primary"
original_date = 2020-08-11

[20200811.registration]
in_person_by = 2020-08-11T19:00:00
# online earlier (ensure name appears on checklist)
# but can vote up to election day
online_by = 2020-08-07
sources = ["https://sos.vermont.gov/elections/voters/registration/", "https://olvr.vermont.gov"]

[20201103]
date = 2020-11-03
name = "General"
original_date = 2020-11-03

[20201103.registration]
in_person_by = 2020-11-03T19:00:00
# online earlier (ensure name appears on checklist)
# but can vote up to election day
online_by = 2020-10-30