name = "Texas"
fips_code = 48
postal_code = "TX"
homepage = "http://www.sos.state.tx.us/elections/index.shtml"
registration_info = "https://www.votetexas.gov/register-to-vote/index.html"
absentee_info = "https://www.sos.texas.gov/elections/voter/reqabbm.shtml"
military_overseas_info = "https://www.votetexas.gov/military-overseas-voters/index.html"
demonym = "Texan"
sos_twitter = "TXsecofstate"
governor_twitter = "GovAbbott"