name = "North Carolina"
fips_code = 37
postal_code = "NC"
homepage = "https://www.ncsbe.gov/index.html"
# registration_info = "https://www.elections.ny.gov/VotingRegister.html"
absentee_info = "https://s3.amazonaws.com/dl.ncsbe.gov/Outreach/Absentee/Infosheet_howtoabsentee_FINAL.pdf"

# change_of_address_lead_time = 20 # days

[[link]]
url = "https://www.sos.ms.gov/content/documents/elections/2020%20Website%20Calendar.pdf"
description = "2020 Calendar PDF"
