# This holds raw scraped data for reference and shouldn't be hand edited.

[20200428]
[20200428.eac]
election_date = 2020-04-28
election_date_str = "April 28, 2020"
name = "Presidential Primary"
notes = ["*See state election office website for information on exceptions to this deadline.", "<em>Updated on February 29, 2020.</em>"]
registration_deadline_str = "April 3, 2020*"

[20200623]
[20200623.eac]
election_date = 2020-06-23
election_date_str = "June 23, 2020"
name = "Congressional Primary"
notes = ["*See state election office website for information on exceptions to this deadline.", "<em>Updated on February 29, 2020.</em>"]
registration_deadline_str = "May 29, 2020*"


[20200623.fec]
create_date = "2019-12-30T10:25:24+00:00"
election_date = "2020-06-23"
election_state = "NY"
election_type_full = "Primary election"
election_type_id = "P"
election_year = 2020
office_sought = "H"
primary_general_date = "2019-12-30T15:25:29.210566"

[20201103]
[20201103.eac]
election_date = 2020-11-03
election_date_str = "November 3, 2020"
name = "General"
notes = ["*See state election office website for information on exceptions to this deadline.", "<em>Updated on February 29, 2020.</em>"]
registration_deadline_str = "October 9, 2020*"

