[20200804]
date = 2020-08-04
name = "Congressional Primary"
original_date = 2020-08-04

[20200804.registration]
online_by = 2020-07-14
receive_by = 2020-07-14
in_person_by = 2020-07-14
sources = [
    "https://sos.kansas.gov/elections/",
    "https://sos.kansas.gov/elections/registration-voting/"
]

[20200804.absentee.application]
receive_by = 2020-07-28
in_person_by = 2020-07-28
sources = [
    "https://sos.kansas.gov/elections/",
    "https://sos.kansas.gov/elections/registration-voting/"
]

[20200804.absentee]
receive_start = 2020-07-15
receive_by = 2020-08-07
postmarked_by = 2020-08-04
in_person_by = 2020-08-04
sources = [
    "https://sos.kansas.gov/elections/",
    "https://sos.kansas.gov/elections/registration-voting/"
]

[20200804.poll.early]
in_person_start = 2020-07-15
in_person_by = 2020-08-03T12:00:00
sources = [
    "https://sos.kansas.gov/elections/",
    "https://sos.kansas.gov/elections/registration-voting/"
]

[20200804.poll]
in_person_by = 2020-08-04
sources = ["https://sos.kansas.gov/elections/"]

[20201103]
date = 2020-11-03
name = "General"
original_date = 2020-11-03

[20201103.registration]
online_by = 2020-10-13
receive_by = 2020-10-13
in_person_by = 2020-10-13
sources = [
    "https://sos.kansas.gov/elections/",
    "https://sos.kansas.gov/elections/registration-voting/"
]

[20201103.absentee.application]
receive_by = 2020-10-27
in_person_by = 2020-10-27
sources = [
    "https://sos.kansas.gov/elections/", 
    "https://sos.kansas.gov/elections/registration-voting/"
]

[20201103.absentee]
receive_start = 2020-10-14
receive_by = 2020-11-06
postmarked_by = 2020-11-03
in_person_by = 2020-11-03
sources = [
    "https://sos.kansas.gov/elections/",
    "https://sos.kansas.gov/elections/registration-voting/"
]

[20201103.poll.early]
in_person_start =  2020-10-14
in_person_by = 2020-11-02T12:00:00
sources = [
    "https://sos.kansas.gov/elections/",
    "https://sos.kansas.gov/elections/registration-voting/"
]

[20201103.poll]
in_person_by = 2020-11-03
sources = ["https://sos.kansas.gov/elections/"]
