[20200818]
date = 2020-08-18
name = "Congressional Primary"
original_date = 2020-08-18

[20200818.registration]
online_by = 2020-07-19
received_by = 2020-07-19
sources = ["https://www.elections.alaska.gov/Core/electiondatesandhours.php"]

[20200818.absentee.application]
received_by = 2020-08-08
sources = ["https://www.elections.alaska.gov/Core/electioncalendar.php"]

[20200818.absentee]
in_person_start = 2020-08-03
postmarked_by = 2020-08-18
received_by = 2020-08-28
sources = [
  "https://www.elections.alaska.gov/Core/electiondatesandhours.php",
  "https://www.elections.alaska.gov/Core/absenteeearlyandinpersonvoting.php",
  "https://www.elections.alaska.gov/Core/electioncalendar.php",
]

[20200818.poll.early]
in_person_start = 2020-08-03

[20200818.poll]
in_person_by = 2020-08-18T20:00:00
in_person_start = 2020-08-18T07:00:00
sources = [
  "https://www.elections.alaska.gov/Core/electiondatesandhours.php",
  "https://www.elections.alaska.gov/Core/absenteeearlyandinpersonvoting.php",
]

[20201103]
date = 2020-11-03
name = "General"
original_date = 2020-11-03

[20201103.registration]
online_by = 2020-10-04
received_by = 2020-10-04
sources = ["https://www.elections.alaska.gov/Core/electiondatesandhours.php"]

[20201103.absentee.application]
received_by = 2020-10-24
sources = ["https://www.elections.alaska.gov/Core/electioncalendar.php"]

[20201103.absentee]
in_person_start = 2020-10-19
postmarked_by = 2020-11-03
received_by = 2020-11-13
sources = [
  "https://www.elections.alaska.gov/Core/electiondatesandhours.php",
  "https://www.elections.alaska.gov/Core/absenteeearlyandinpersonvoting.php",
  "https://www.elections.alaska.gov/Core/electioncalendar.php",
]

[20201103.poll.early]
in_person_start = 2020-10-19

[20201103.poll]
in_person_by = 2020-11-03T20:00:00
in_person_start = 2020-11-03T07:00:00
sources = [
  "https://www.elections.alaska.gov/Core/electiondatesandhours.php",
  "https://www.elections.alaska.gov/Core/absenteeearlyandinpersonvoting.php",
]
