# This holds raw scraped data for reference and shouldn't be hand edited.

[20200801]
[20200801.eac]
election_date = 2020-08-01
election_date_str = "August 1, 2020"
name = "Congressional Primary"
notes = ["<br /><em>Updated on February 28, 2020.</em>"]
registration_deadline = 2020-07-02
registration_deadline_str = "July 2, 2020"


[20200801.fec]
create_date = "2019-12-30T11:57:44+00:00"
election_date = "2020-08-01"
election_state = "VI"
election_type_full = "Primary election"
election_type_id = "P"
election_year = 2020
office_sought = "H"
primary_general_date = "2019-12-30T16:57:50.480494"

[20201103]
[20201103.eac]
election_date = 2020-11-03
election_date_str = "November 3, 2020"
name = "General"
notes = ["<br /><em>Updated on February 28, 2020.</em>"]
registration_deadline = 2020-10-03
registration_deadline_str = "October 3, 2020"


[20200606]
[20200606.fec]
create_date = "2020-01-09T16:50:22+00:00"
election_date = "2020-06-06"
election_party = "DEM"
election_state = "VI"
election_type_id = "CAU"
election_year = 2020
office_sought = "P"
primary_general_date = "2020-01-09T21:50:32.965041"
update_date = "2020-01-31T14:57:42+00:00"

