name = "Rhode Island"
fips_code = 44
postal_code = "RI"
homepage = "https://vote.sos.ri.gov/"
registration_info = "https://vote.sos.ri.gov/Home/RegistertoVote?ActiveFlag=1"
absentee_info = "https://vote.sos.ri.gov/Voter/VotebyMail"
military_overseas_info = "https://vote.sos.ri.gov/Voter/VotebyMail"
demonym = "Rhode Islander"

sos_twitter = ["risecstate", "NellieGorbea"]
boe_twitter = "RI_BOE"
gov_twitter = "GovRaimondo"
