[20200808]
date = 2020-08-08
name = "Congressional Primary"
original_date = 2020-08-08

[20200808.registration]
online_by = 2020-07-09T16:30:00
postmarked_by = 2020-07-09
in_person_by = 2020-08-08
sources = [
    "https://elections.hawaii.gov/about-us/calendar/",
    "https://elections.hawaii.gov/voter-service-centers-and-places-of-deposit/"
]

[20200808.absentee.application]
received_by = 2020-08-01T16:30:00
in_person_by = 2020-08-01T16:30:00
sources = ["https://elections.hawaii.gov/about-us/calendar/"]

[20200808.absentee]
received_by = 2020-08-08T19:00:00
sources = ["https://elections.hawaii.gov/frequently-asked-questions/voting-by-mail/"]

[20200808.poll.early]
in_person_start = 2020-08-03
in_person_by = 2020-08-08T19:00:00
sources = [
    "https://elections.hawaii.gov/about-us/calendar/",
    "https://elections.hawaii.gov/voter-service-centers-and-places-of-deposit/"
]

[20200808.poll]
in_person_start = 2020-08-08
in_person_by = 2020-08-08T19:00:00
sources = ["https://elections.hawaii.gov/about-us/calendar/"]

[20201103]
date = 2020-11-03
name = "General"
original_date = 2020-11-03

[20201103.registration]
online_by = 2020-10-05T16:30:00
postmarked_by = 2020-10-05
in_person_by = 2020-11-03
sources = [
    "https://elections.hawaii.gov/about-us/calendar/"
    "https://elections.hawaii.gov/voter-service-centers-and-places-of-deposit/"
]

[20201103.absentee.application]
received_by = 2020-10-27T16:30:00
in_person_by = 2020-10-27T16:30:00
sources = ["https://elections.hawaii.gov/about-us/calendar/"]

[20201103.absentee]
received_by = 2020-11-03T19:00:00
sources = ["https://elections.hawaii.gov/frequently-asked-questions/voting-by-mail/"]

[20201103.poll.early]
in_person_start = 2020-10-20
in_person_by = 2020-11-03T19:00:00
sources = [
    "https://elections.hawaii.gov/about-us/calendar/",
    "https://elections.hawaii.gov/voter-service-centers-and-places-of-deposit/"
]

[20201103.poll]
in_person_start = 2020-11-03T07:00:00
in_person_by = 2020-1-03T19:00:00
sources = ["https://elections.hawaii.gov/about-us/calendar/"]
