# This holds raw scraped data for reference and shouldn't be hand edited.

[20200303]
[20200303.eac]
election_date = 2020-03-03
election_date_str = "March 3, 2020"
name = "Presidential Primary (Democrats)"
notes = ["<em>Updated on June 1, 2020.</em>"]
registration_deadline = 2020-02-10
registration_deadline_str = "February 10, 2020"

[20200623]
[20200623.eac]
election_date = 2020-06-23
election_date_str = "June 23, 2020"
name = "Congressional Primary"
notes = ["<em>Updated on June 1, 2020.</em>"]
registration_deadline = 2020-05-26
registration_deadline_str = "May 26, 2020"


[20200623.fec]
create_date = "2019-12-30T11:55:56+00:00"
election_date = "2020-06-23"
election_notes = "Moved from 6/09/2020.  (COVID-19)"
election_state = "VA"
election_type_full = "Primary election"
election_type_id = "P"
election_year = 2020
office_sought = "S"
primary_general_date = "2019-12-30T16:56:01.463367"
update_date = "2020-04-15T13:18:27+00:00"

[20201103]
[20201103.eac]
election_date = 2020-11-03
election_date_str = "November 3, 2020"
name = "General"
notes = ["<em>Updated on June 1, 2020.</em>"]
registration_deadline = 2020-10-13
registration_deadline_str = "October 13, 2020"


[20200718]
[20200718.fec]
create_date = "2020-05-15T10:00:22+00:00"
election_date = "2020-07-18"
election_district = 7
election_notes = "Was rescheduled from 4/25/2020.  (COVID-19)"
election_party = "REP"
election_state = "VA"
election_type_full = "Convention"
election_type_id = "C"
election_year = 2020
office_sought = "H"
primary_general_date = "2020-05-15T14:00:29.837518"

[20200627]
[20200627.fec]
create_date = "2020-05-13T16:24:55+00:00"
election_date = "2020-06-27"
election_district = 4
election_notes = "Was rescheduled from 4/25/2020.  (COVID-19)"
election_party = "REP"
election_state = "VA"
election_type_full = "Convention"
election_type_id = "C"
election_year = 2020
office_sought = "H"
primary_general_date = "2020-05-13T20:25:01.497232"

[20200620]
[20200620.fec]
create_date = "2020-05-15T12:20:01+00:00"
election_date = "2020-06-20"
election_district = 10
election_notes = "Was rescheduled from 5/30/2020.  (COVID-19)"
election_party = "REP"
election_state = "VA"
election_type_full = "Convention"
election_type_id = "C"
election_year = 2020
office_sought = "H"
primary_general_date = "2020-05-15T16:20:05.866091"

[20200613]
[20200613.fec]
create_date = "2020-05-12T16:24:13+00:00"
election_date = "2020-06-13"
election_district = 5
election_notes = "District 5 Convention date of 6/13/20, set by party on 5/11/2020. (COVID-19).  (Originally set for 4/25/20, but was postponed.)"
election_party = "REP"
election_state = "VA"
election_type_full = "Convention"
election_type_id = "C"
election_year = 2020
office_sought = "H"
primary_general_date = "2020-05-13T05:20:05.023207"

