name = "Virginia"
fips_code = 51
postal_code = "VA"

homepage = "https://www.elections.virginia.gov/"
registration_info = "https://www.elections.virginia.gov/registration/"
registration_url = "https://www.elections.virginia.gov/citizen-portal/"

[[link]]
description = "Upcoming Elections"
url = "https://www.elections.virginia.gov/casting-a-ballot/calendars-schedules/upcoming-elections.html"
