[20200303]
date = 2020-03-03
name = "Presidential Primary"
original_date = 2020-03-03

[20200630]
date = 2020-06-30
name = "Congressional Primary"
original_date = 2020-06-30
sources = [
    "https://www.ok.gov/elections/Election_Info/2020_Election_Calendar.html"
]

[20200630.register]
received_by = 2020-06-05
in_person_by = 2020-06-05
sources = [
    "https://www.ok.gov/elections/Voter_Info/Register_to_Vote/",
    "https://www.ok.gov/elections/Election_Info/2020_Election_Calendar.html"
]

[20200630.absentee.application]
received_by = 2020-06-23T17:00:00
in_person_by = 2020-06-23T17:00:00
sources = [
    "https://www.ok.gov/elections/Voter_Info/Absentee_Voting/",
    "https://www.ok.gov/elections/Election_Info/2020_Election_Calendar.html"
]

[20200630.absentee]
received_by = 2020-06-30T19:00:00
in_person_start = 2020-06-25T08:00:00
in_person_by = 2020-06-29T17:00:00
sources = [
    "https://www.ok.gov/elections/Voter_Info/Absentee_Voting/",
    "https://www.ok.gov/elections/Election_Info/2020_Election_Calendar.html"
]

[20200630.poll.early]
in_person_start = 2020-06-25T08:00:00
in_person_by = 2020-06-27T14:00:00
sources = [
    "https://www.ok.gov/elections/Early_Voting.html",
    "https://www.ok.gov/elections/Election_Info/2020_Election_Calendar.html"
]

[20200630.poll]
in_person_start = 2020-06-30T07:00:00
in_person_by = 2020-06-30T19:00:00
sources = [
    "https://www.ok.gov/elections/Election_Info/2020_Election_Calendar.html"
]

[20200825]
date = 2020-08-25
name = "Congressional Primary Run-off (if needed)"
original_date = 2020-08-25
sources = [
    "https://www.ok.gov/elections/Election_Info/2020_Election_Calendar.html"
]

[20200825.register]
received_by = 2020-07-31
in_person_by = 2020-07-31
sources = [
    "https://www.ok.gov/elections/Voter_Info/Register_to_Vote/",
    "https://www.ok.gov/elections/Election_Info/2020_Election_Calendar.html"
]

[20200825.absentee.application]
received_by = 2020-08-18T17:00:00
in_person_by = 2020-08-18T17:00:00
sources = [
    "https://www.ok.gov/elections/Voter_Info/Absentee_Voting/",
    "https://www.ok.gov/elections/Election_Info/2020_Election_Calendar.html"
]

[20200825.poll.early]
in_person_start = 2020-08-20T08:00:00
in_person_by = 2020-08-22T14:00:00
sources = [
    "https://www.ok.gov/elections/Early_Voting.html",
    "https://www.ok.gov/elections/Election_Info/2020_Election_Calendar.html"
]

[20200825.poll]
in_person_start = 2020-08-25T07:00:00
in_person_by = 2020-08-25T19:00:00
sources = [
    "https://www.ok.gov/elections/Election_Info/2020_Election_Calendar.html"
]

[20201103]
date = 2020-11-03
name = "General"
original_date = 2020-11-03
sources = [
    "https://www.ok.gov/elections/Election_Info/2020_Election_Calendar.html"
]

[20201103.register]
received_by = 2020-10-09
in_person_by = 2020-10-09
sources = [
    "https://www.ok.gov/elections/Voter_Info/Register_to_Vote/",
    "https://www.ok.gov/elections/Election_Info/2020_Election_Calendar.html"
]

[20201103.absentee.application]
received_by = 2020-10-27T17:00:00
in_person_by = 2020-10-27T17:00:00
sources = [
    "https://www.ok.gov/elections/Voter_Info/Absentee_Voting/",
    "https://www.ok.gov/elections/Election_Info/2020_Election_Calendar.html"
]

[20201103.poll.early]
in_person_start = 2020-10-29T08:00:00
in_person_by = 2020-10-31T14:00:00
sources = [
    "https://www.ok.gov/elections/Early_Voting.html",
    "https://www.ok.gov/elections/Election_Info/2020_Election_Calendar.html"
]

[20201103.poll]
in_person_start = 2020-11-03T07:00:00
in_person_by = 2020-11-03T19:00:00
sources = [
    "https://www.ok.gov/elections/Election_Info/2020_Election_Calendar.html"
]
