# This holds raw scraped data for reference and shouldn't be hand edited.

[20200303]
[20200303.eac]
election_date = 2020-03-03
election_date_str = "March 3, 2020"
name = "Presidential Primary"
notes = ["<em>Updated on February 29, 2020.</em>"]
registration_deadline = 2020-02-07
registration_deadline_str = "February 7, 2020"

[20200630]
[20200630.eac]
election_date = 2020-06-30
election_date_str = "June 30, 2020"
name = "Congressional Primary"
notes = ["<em>Updated on February 29, 2020.</em>"]
registration_deadline = 2020-06-05
registration_deadline_str = "June 5, 2020"


[20200630.fec]
create_date = "2019-12-30T10:43:15+00:00"
election_date = "2020-06-30"
election_state = "OK"
election_type_full = "Primary election"
election_type_id = "P"
election_year = 2020
office_sought = "H"
primary_general_date = "2019-12-30T15:43:20.508922"

[20200825]
[20200825.eac]
election_date = 2020-08-25
election_date_str = "August 25, 2020"
name = "Congressional Primary Run-off (if needed)"
notes = ["<em>Updated on February 29, 2020.</em>"]
registration_deadline = 2020-07-31
registration_deadline_str = "July 31, 2020"


[20200825.fec]
create_date = "2019-12-30T10:44:15+00:00"
election_date = "2020-08-25"
election_state = "OK"
election_type_full = "Primary runoff"
election_type_id = "PR"
election_year = 2020
office_sought = "H"
primary_general_date = "2019-12-30T15:44:21.020456"

[20201103]
[20201103.eac]
election_date = 2020-11-03
election_date_str = "November 3, 2020"
name = "General"
notes = ["<em>Updated on February 29, 2020.</em>"]
registration_deadline = 2020-10-09
registration_deadline_str = "October 9, 2020"

