[20200303]
date = 2020-03-03
name = "Presidential Primary"
original_date = 2020-03-03

[20200630]
date = 2020-06-30
name = "Congressional Primary"
original_date = 2020-06-30

[20200630.absentee.application]
received_by = 2020-06-22
sources = "https://www.sos.state.co.us/pubs/elections/calendar.html"

[20200630.registration]
received_by = 2020-06-22
in_person_by = 2020-06-30
sources = "https://www.sos.state.co.us/pubs/elections/calendar.html"

[20200630.poll.early]
in_person_start = 2020-06-23
in_person_by = 2020-06-30
sources = "https://www.sos.state.co.us/pubs/elections/calendar.html"

[20200630.poll]
in_person_by = 2020-06-30
sources = "https://www.sos.state.co.us/pubs/elections/calendar.html"

[20200630.poll.overseas_military]
received_by = 2020-07-08
sources = "https://www.sos.state.co.us/pubs/elections/calendar.html"


[20201103]
date = 2020-11-03
name = "General"
original_date = 2020-11-03

[20201103.registration]
received_by = 2020-10-26
in_person_by = 2020-11-03
sources = "https://www.sos.state.co.us/pubs/elections/calendar.html"

[20201103.absentee.application]
received_by = 2020-10-26
sources = "https://www.sos.state.co.us/pubs/elections/calendar.html"

[20201103.poll.early]
in_person_start = 2020-10-19
in_person_by = 2020-11-03
sources = "https://www.sos.state.co.us/pubs/elections/calendar.html"

[20201103.poll]
in_person_by = 2020-11-03
sources = "https://www.sos.state.co.us/pubs/elections/calendar.html"

[20200630.poll.overseas_military]
received_by = 2020-11-12
sources = "https://www.sos.state.co.us/pubs/elections/calendar.html"