name = "Wisconsin"
fips_code = 55
postal_code = "WI"
homepage = "http://elections.wi.gov/elections-voting"
registration_info = "https://myvote.wi.gov/en-us/RegisterOnline"
absentee_info = "https://elections.wi.gov/voters/absentee"
military_info = "https://elections.wi.gov/voters/military"
overseas_info = "https://elections.wi.gov/voters/overseas"
demonym = "Wisconsinite"
