[20200602]
date = 2020-06-02
name = "Congressional & Presidential Primary"
original_date = 2020-06-02
results = "https://enr.indianavoters.in.gov/site/index.html"

[20201103]
date = 2020-11-03
name = "General"
original_date = 2020-11-03
