# This holds raw scraped data for reference and shouldn't be hand edited.

[20200609]
[20200609.eac]
election_date = 2020-06-09
election_date_str = "June 9, 2020"
name = "Congressional Primary"
notes = ["<em>Updated on May 8, 2020.</em>"]
registration_deadline = 2020-05-11
registration_deadline_str = "May 11, 2020"


[20200609.fec]
create_date = "2019-12-27T15:08:17+00:00"
election_date = "2020-06-09"
election_notes = "Delayed from 3/24/2020, and then from 5/19/2020.  (COVID-19)\r\n"
election_state = "GA"
election_type_full = "Primary election"
election_type_id = "P"
election_year = 2020
office_sought = "P"
primary_general_date = "2019-12-27T20:08:22.815117"
update_date = "2020-04-10T15:18:19+00:00"

[20200811]
[20200811.eac]
election_date = 2020-08-11
election_date_str = "August 11, 2020"
name = "Congressional Primary Run-off (if needed)"
notes = ["<em>Updated on May 8, 2020.</em>"]
registration_deadline = 2020-07-13
registration_deadline_str = "July 13, 2020"


[20200811.fec]
create_date = "2020-01-03T15:22:25+00:00"
election_date = "2020-08-11"
election_notes = "Delayed from 7/21/2020. (COVID-19)"
election_state = "GA"
election_type_full = "Primary runoff"
election_type_id = "PR"
election_year = 2020
office_sought = "S"
primary_general_date = "2020-01-03T20:22:30.632160"
update_date = "2020-04-10T15:20:13+00:00"

[20201103]
[20201103.eac]
election_date = 2020-11-03
election_date_str = "November 3, 2020"
name = "General"
notes = ["<em>Updated on May 8, 2020.</em>"]
registration_deadline = 2020-10-05
registration_deadline_str = "October 5, 2020"


[20201103.fec]
create_date = "2020-04-01T14:01:01+00:00"
election_date = "2020-11-03"
election_notes = "Senator Johnny Isakson's Seat."
election_state = "GA"
election_type_full = "Special election general"
election_type_id = "SG"
election_year = 2020
office_sought = "S"
primary_general_date = "2020-04-01T18:01:08.003477"

[20210105]
[20210105.eac]
election_date = 2021-01-05
election_date_str = "January 5, 2021"
name = "General Run-Off (if needed)"
notes = ["<em>Updated on May 8, 2020.</em>"]
registration_deadline = 2020-12-07
registration_deadline_str = "December 7, 2020"

