[20200317]
date = 2020-03-17
name = "Presidential Preference (Democrats)"
original_date = 2020-03-17

[20200804]
date = 2020-08-04
name = "Congressional Primary"
original_date = 2020-08-04

[20200804.registration]
online_by = 2020-07-06
in_person_by = 2020-07-06
received_by = 2020-07-06
sources = [
    "https://azsos.gov/elections/elections-calendar-upcoming-events",
    "https://servicearizona.com/VoterRegistration/register?execution=e1s1"
]


[20200804.absentee.application]
online_by = 2020-07-24T17:00:00
call_by = 2020-07-24T17:00:00
email_by = 2020-07-24T17:00:00
received_by = 2020-07-24T17:00:00
in_person_by = 2020-07-24T17:00:00
sources = ["https://azsos.gov/votebymail"]

[20200804.absentee]
received_by = 2020-08-04T19:00:00
in_person_by = 2020-08-04T19:00:00
sources = ["https://azsos.gov/votebymail"]

# [20200804.poll.early]
# Varies by County
# sources = ["https://azsos.gov/votebymail"]

[20200804.poll]
in_person_by = 2020-08-04T19:00:00

[20201103]
date = 2020-11-03
name = "General"
original_date = 2020-11-03

[20201103.registration]
online_by = 2020-10-05
in_person_by = 2020-10-05
received_by = 2020-10-05
sources = [
    "https://azsos.gov/elections/elections-calendar-upcoming-events"
    "https://servicearizona.com/VoterRegistration/register?execution=e1s1"
]


[20201103.absentee.application]
online_by = 2020-10-23T17:00:00
call_by = 2020-10-23T17:00:00
email_by = 2020-10-23T17:00:00
received_by = 2020-10-23T17:00:00
in_person_by = 2020-10-23T17:00:00
sources = ["https://azsos.gov/votebymail"]


[20201103.absentee]
received_by = 2020-11-03T19:00:00
in_person_by = 2020-11-03T19:00:00
sources = ["https://azsos.gov/votebymail"]

# [20200804.poll.early]
# Varies by County
# sources = ["https://azsos.gov/votebymail"]

[20201103.poll]
in_person_by = 2020-11-03T19:00:00
