# This holds raw scraped data for reference and shouldn't be hand edited.

[20200229]
[20200229.eac]
election_date = 2020-02-29
election_date_str = "February 29, 2020"
name = "Presidential Primary (Democrats)"
notes = ["*See state election office website for information on exceptions to this deadline.", "<em>Updated on February 29, 2020.</em>"]
registration_deadline = 2020-01-30
registration_deadline_str = "January 30, 2020"

[20200609]
[20200609.eac]
election_date = 2020-06-09
election_date_str = "June 9, 2020"
name = "Congressional Primary"
notes = ["*See state election office website for information on exceptions to this deadline.", "<em>Updated on February 29, 2020.</em>"]
registration_deadline_str = "May 8, 2020 (in-person)*"


[20200609.fec]
create_date = "2019-12-30T11:01:30+00:00"
election_date = "2020-06-09"
election_state = "SC"
election_type_full = "Primary election"
election_type_id = "P"
election_year = 2020
office_sought = "S"
primary_general_date = "2019-12-30T16:01:35.613791"


[20200609.google_civic]
electionDay = "2020-06-09"
id = "4971"
last_fetched = "2020-06-10"
name = "South Carolina State Primary Election"
ocdDivisionId = "ocd-division/country:us/state:sc"

[20200623]
[20200623.eac]
election_date = 2020-06-23
election_date_str = "June 23, 2020"
name = "Congressional Primary Run-Off (if needed)"
notes = ["*See state election office website for information on exceptions to this deadline.", "<em>Updated on February 29, 2020.</em>"]
registration_deadline_str = "May 8, 2020 (in-person)*"


[20200623.fec]
create_date = "2019-12-30T11:02:54+00:00"
election_date = "2020-06-23"
election_state = "SC"
election_type_full = "Primary runoff"
election_type_id = "PR"
election_year = 2020
office_sought = "H"
primary_general_date = "2019-12-30T16:03:00.619053"
update_date = "2019-12-30T11:03:37+00:00"

[20201103]
[20201103.eac]
election_date = 2020-11-03
election_date_str = "November 3, 2020"
name = "General"
notes = ["*See state election office website for information on exceptions to this deadline.", "<em>Updated on February 29, 2020.</em>"]
registration_deadline_str = "October 2, 2020 (in-person)*"


[20200613]
[20200613.fec]
create_date = "2020-04-07T16:56:17+00:00"
election_date = "2020-06-13"
election_party = "LIB"
election_state = "SC"
election_type_full = "Convention"
election_type_id = "C"
election_year = 2020
office_sought = "S"
primary_general_date = "2020-04-07T20:56:22.787286"

